site_name: Bryce's Homelab Documentation
site_url: https://BryceA-IT.github.io/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
plugins:
  - search
nav:
  - Home: index.md
  - Projects:
      - Linksys WHW01 Mesh: projects/linksys-whw01-mesh.md
  - Windows LAB:
      - Overview: LAB/Windows/index.md
      - Hyper-V Setup: LAB/Windows/HyperV-Environment-Setup.md
      - OPNsense Installation: LAB/Windows/Installing-OPNsense.md
      - Domain Controller: LAB/Windows/Installing-DomainController.md
  - Network Configuration: network/topology.md